# Config Stage Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stagepod
  labels:
    app: stagepod
spec:
  selector:
    matchLabels:
      app: stagepod
  template:
    metadata:
      labels:
        app: stagepod
    spec:
    # Config Containers
      containers:
      - name: front
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      - name: back
        image: debian
        command: ["sleep", "3600"]
---
# Config Service
apiVersion: v1
kind: Service
metadata:
  name: stageservice
  labels:
    app: fb
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: stage